### ISSUE TITLE
Script not working.

### ISSUE THREAD

**Issue by VII86** [ScriptKi77y/bread-script#1]
Script loads API but doesn't redirect to any thread. (FF 43.0.3 / Greasemonkey )

Console output:
Initializing functions... bread.user.js:746:5
Subject:  Pedo Thread bread.user.js:163:33
Array [ "Pedo", "Thread" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Subject:  PUBLIC SERVICE ANNOUNCEMENT bread.user.js:163:33
Array [ "PUBLIC", "SERVICE", "ANNOUNCEMENT" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
Subject:  China commissions second aircraft carrier. bread.user.js:163:33
Array [ "China", "commissions", "second", "aircraft", "carrier." ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Subject:  What does /b/ think of South Korea? bread.user.js:163:33
Array [ "What", "does", "/b/", "think", "of", "South", "Korea?" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Subject:  /b/ is for booty. bread.user.js:163:33
Array [ "/b/", "is", "for", "booty." ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
Subject:  The lulzicate Project bread.user.js:163:33
Array [ "The", "lulzicate", "Project" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Subject:  Anti-Christian memes bread.user.js:163:33
Array [ "Anti-Christian", "memes" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
Subject:  NoFap 2016  bread.user.js:163:33
Array [ "NoFap", "2016", "" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Subject:  Texting your crush bread.user.js:163:33
Array [ "Texting", "your", "crush" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Subject:  embarrasing stories bread.user.js:163:33
Array [ "embarrasing", "stories" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Subject:  That building bread.user.js:163:33
Array [ "That", "building" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
Subject:  I did it guys bread.user.js:163:33
Array [ "I", "did", "it", "guys" ] bread.user.js:219:9
Subject test:  0 bread.user.js:165:33
Subject:  Opiates Thread bread.user.js:163:33
Array [ "Opiates", "Thread" ] bread.user.js:219:9
Subject test:  2 bread.user.js:165:33
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
TypeError: thread.sub is undefined
Stack-Trace:
locateBread/this.init/This.xml.onload/<@chrome://greasemonkey-modules/content/sandbox.js -> file:///C:/Users/Luffy/AppData/Roaming/Mozilla/Firefox/Profiles/qzzp1hsj.default-1420139537801/gm_scripts/bread_script/bread.user.js:160:29
 bread.user.js:181:29
Array [  ]

**Comment by ScriptKi77y** [comment]
This is actually happening because 8ch suffers I/O issues, the developers truncated the API to 2 pages worth of threads.

The threads after they have dropped past page 2 will never show up in the API and the script never finds them...

The only alternative is to parse the HTML itself, not the best practice really.

**Comment by VII86** [comment]
Man that sucks. Maybe you could add a routine so that the script says that it can't find a valid thread? And then stopping all the stuff in back? If you keep it open, it really slows down FF. ~
